export const tabs = [
  "batteries-directory",
  "districts-directory",
  "objects-directory",
  "other-equipment-directory",
  "ups-models-directory",
  "total-table",
  "receiving-batteries",
  "equipment-card",
];

const tableState = {
  "batteries-directory": {
    name: "Довідник АКБ",
    headColumnData: [
      {
        name: "rowNumber",
        label: "№",
        initial: null,
        filter: true,
        sort: true,
        width: 60,
        maxWidth: 10,
      },
      {
        name: "typeBattery",
        label: "Тип АКБ",
        initial: null,
        filter: true,
        sort: true,
        width: 120,
        maxWidth: 120,
      },
      {
        name: "a_h",
        label: "А/ч",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "actions",
        label: "Дії",
        initial: null,
        filter: false,
        sort: false,
        width: 100,
        maxWidth: 100,
      },
    ],
    exceptionKeyColumn: ["id"],
    initialFilters: {
      id: null,
      typeBattery: null,
      a_h: null,
    },
    rcspan: false,
    expandbleRow: false,
    actionMode: "modify",
    staticHeight: 288,
  },
  "districts-directory": {
    name: "Довідник структурних підрозділів",
    headColumnData: [
      {
        name: "expander",
        label: "",
        initial: null,
        filter: false,
        sort: false,
        width: 20,
        maxWidth: 20,
      },
      {
        name: "name",
        label: "Філія",
        initial: null,
        filter: true,
        sort: true,
        width: "auto",
        maxWidth: 60,
      },
      {
        name: "actions",
        label: "Дії",
        initial: null,
        filter: false,
        sort: false,
        width: "auto",
        maxWidth: 60,
      },
    ],
    exceptionKeyColumn: ["id", "branchesDirectoryId", "districtsDirectories"],
    initialFilters: {
      id: null,
      name: null,
    },
    rcspan: false,
    expandbleRow: true,
    actionMode: "modify",
    staticHeight: 288,
  },
  "objects-directory": {
    name: "Довідник об'єктів",
    headColumnData: [
      {
        name: "rowNumber",
        label: "№",
        initial: null,
        filter: true,
        sort: true,
        width: 60,
        maxWidth: 40,
      },
      {
        name: "districtName",
        label: "Структурний підрозділ",
        initial: null,
        filter: true,
        sort: true,
        width: 200,
        maxWidth: 200,
      },
      {
        name: "objectName",
        label: "Назва об'єкту",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "voltage",
        label: "Напруга",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },

      {
        name: "actions",
        label: "Дії",
        initial: null,
        filter: false,
        sort: false,
        width: 100,
        maxWidth: 100,
      },
    ],
    exceptionKeyColumn: ["id"],
    initialFilters: {
      id: null,
      objectName: null,
      voltage: null,
      districtName: null,
    },
    rcspan: false,
    expandbleRow: false,
    actionMode: "modify",
    staticHeight: 288,
  },
  "other-equipment-directory": {
    name: "Довідник іншого обладнання",
    headColumnData: [
      {
        name: "rowNumber",
        label: "№",
        initial: null,
        filter: true,
        sort: true,
        width: 60,
        maxWidth: 60,
      },
      {
        name: "producer",
        label: "Виробник",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "model",
        label: "Модель",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "typeBattery",
        label: "Встановленний тип АКБ на дату створення ПЗ",
        initial: null,
        filter: true,
        sort: true,
        width: 180,
        maxWidth: 180,
      },
      {
        name: "numberOfBattery",
        label: "Кількість АКБ",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "dateOfLastBatteryReplacement",
        label: "Дата останньої заміни АКБ",
        initial: null,
        filter: true,
        sort: true,
        width: 120,
        maxWidth: 120,
      },
      {
        name: "actions",
        label: "Дії",
        initial: null,
        filter: false,
        sort: false,
        width: 60,
        maxWidth: 60,
      },
    ],
    exceptionKeyColumn: ["id", "batteriesDirectoryId"],
    initialFilters: {
      id: null,
      producer: null,
      model: null,
      typeBattery: null,
      numberOfBatteries: null,
      dateOfLastBatteryReplacement: null,
    },
    rcspan: false,
    expandbleRow: false,
    actionMode: "modify",
    staticHeight: 288,
  },
  "ups-models-directory": {
    name: "Довідник моделей ДБЖ",
    headColumnData: [
      {
        name: "rowNumber",
        label: "№",
        initial: null,
        filter: true,
        sort: true,
        width: 60,
        maxWidth: 60,
      },
      {
        name: "power",
        label: "Потужність, VA",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "inventoryNumber",
        label: "Інв.№",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "s_n",
        label: "s/n",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "yearProductionUPS",
        label: "Рік випуску ДБЖ",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },

      {
        name: "apcs",
        label: "АСУ ТП",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "object",
        label: "Об'єкт розміщення",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "actions",
        label: "Дії",
        initial: null,
        filter: false,
        sort: false,
        width: 60,
        maxWidth: 60,
      },
    ],
    exceptionKeyColumn: [
      "id",
      "batteriesDirectoryId",
      "otherEquipmentDirectoryId",
      "dateOfLastBatteryReplacement",
      "districtsDirectoryId",
      "branchesDirectoryId",
      "upsModelsDirectoryid",
      "objectsDirectoryId",
    ],
    initialFilters: {
      id: null,
      objectName: null,
      voltage: null,
      districtName: null,
    },
    rcspan: false,
    expandbleRow: false,
    actionMode: "modify",
    staticHeight: 288,
  },
  "total-table": {
    name: "Облік заміни АКБ",
    headColumnData: [
      {
        name: "rowNumber",
        label: "№",
        initial: null,
        filter: false,
        sort: true,
        colspan: 1,
        rowspan: 2,
        width: 20,
        maxWidth: 50,
      },
      {
        name: "object",
        label: "Об'єкт",
        initial: null,
        filter: false,
        sort: false,
        colspan: 3,
        rowspan: 1,
        width: 20,
        maxWidth: 20,
      },
      {
        name: "producer",
        label: "Виробник",
        initial: null,
        filter: true,
        sort: true,
        colspan: 1,
        rowspan: 2,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "model",
        label: "Модель",
        initial: null,
        filter: true,
        sort: true,
        colspan: 1,
        rowspan: 2,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "voltage",
        label: "Потужність",
        initial: null,
        filter: false,
        sort: true,
        colspan: 1,
        rowspan: 2,
        width: 20,
        maxWidth: 20,
      },
      {
        name: "numberOfBatteries",
        label: "К-сть АКБ",
        initial: null,
        filter: false,
        sort: true,
        colspan: 1,
        rowspan: 2,
        width: 80,
        maxWidth: 80,
      },
      {
        name: "inventoryNumber",
        label: "Інвентарний номер",
        initial: null,
        filter: false,
        sort: true,
        colspan: 1,
        rowspan: 2,
        width: 20,
        maxWidth: 20,
      },
      {
        name: "typeBattery",
        label: "Встановлений тип АКБ",
        initial: null,
        filter: true,
        sort: true,
        colspan: 1,
        rowspan: 2,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "dateOfLastBatteryReplacement",
        label: "Дата останньої заміни АКБ",
        initial: null,
        filter: true,
        sort: true,
        colspan: 1,
        rowspan: 2,
        width: 120,
        maxWidth: 120,
      },
    ],

    exceptionKeyColumn: [
      "id",
      "upsModelsDirectoryId",
      "batteryId",
      "districtId",
      "objectId",
      "equipmentCardId",
      "actions",
    ],
    initialFilters: {
      id: null,
      producer: null,
      model: null,
      voltage: null,
      numberOfBatteries: null,
      inventoryNumber: null,
      typeBattery: null,
      dateOfLastBatteryReplacement: null,
    },
    rcspan: true,
    expandbleRow: false,
    actionMode: "modify",
    staticHeight: 236,
  },
  "receiving-batteries": {
    name: "Отримання АКБ",
    headColumnData: [
      {
        name: "rowNumber",
        label: "№",
        initial: null,
        filter: false,
        sort: true,
        width: 100,
      },
      {
        name: "dateOfReceiving",
        label: "Дата отримання",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
      },
      {
        name: "typeBattery",
        label: "Тип АКБ",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
      },
      {
        name: "numbers",
        label: "Кількість",
        initial: null,
        filter: false,
        sort: true,
        width: 100,
      },
      {
        name: "currentBalance",
        label: "Поточний залишок",
        initial: null,
        filter: false,
        sort: true,
        width: 100,
      },
      {
        name: "contract",
        label: "Номер договору",
        initial: null,
        filter: false,
        sort: true,
        width: 100,
      },
      {
        name: "contractDate",
        label: "Дата договору",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
      },
      {
        name: "counterparty",
        label: "Контрагент",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
      },

      {
        name: "actions",
        label: "Дії",
        initial: null,
        filter: false,
        sort: false,
        width: 100,
      },
    ],
    exceptionKeyColumn: ["id", "batteriesDirectoryId", "receiptId"],

    initialFilters: {
      id: null,
      dateOfReceiving: null,
      typeBattery: null,
      numbers: null,
      currentBalance: null,
      contract: null,
      contractDate: null,
      counterparty: null,
    },
    rcspan: false,
    expandbleRow: false,
    actionMode: "add",
    staticHeight: 288,
  },
  "equipment-card": {
    name: "Картка обладнання",
    headColumnData: [
      {
        name: "rowNumber",
        label: "№",
        initial: null,
        filter: false,
        sort: true,
        width: 20,
        maxWidth: 20,
      },
      {
        name: "producer",
        label: "Виробник",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "model",
        label: "Модель",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "voltage",
        label: "Потужність",
        initial: null,
        filter: false,
        sort: true,
        width: 70,
        maxWidth: 70,
      },
      {
        name: "typeBattery",
        label: "Встановлений тип АКБ",
        initial: null,
        filter: true,
        sort: true,
        width: 160,
        maxWidth: 160,
      },
      {
        name: "numberOfBatteries",
        label: "К-сть АКБ",
        initial: null,
        filter: false,
        sort: true,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "yearProductionUPS",
        label: "Рік випуску",
        initial: null,
        filter: true,
        sort: true,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "inventoryNumber",
        label: "Інвентарний номер",
        initial: null,
        filter: true,
        sort: true,
        width: 150,
        maxWidth: 150,
      },
      {
        name: "s_n",
        label: "s/n",
        initial: null,
        filter: false,
        sort: true,
        width: 40,
        maxWidth: 40,
      },
      {
        name: "apcs",
        label: "АСУ ТП",
        initial: null,
        filter: false,
        sort: true,
        width: 80,
        maxWidth: 80,
      },
      {
        name: "batteryReplacement",
        label: "Заміна АКБ",
        initial: null,
        filter: false,
        sort: false,
        width: 80,
        maxWidth: 80,
      },
    ],
    exceptionKeyColumn: [
      "id",
      "upsModelsDirectoryId",
      "batteriesDirectoryId",
      "otherEquipmentDirectoryId",
    ],

    initialFilters: {
      id: null,
      producer: null,
      model: null,
      voltage: null,
      numberOfBatteries: null,
      inventoryNumber: null,
      typeBattery: null,
      dateOfLastBatteryReplacement: null,
    },
    rcspan: false,
    expandbleRow: false,
    actionMode: "add",
    staticHeight: 288,
  },
  "battery-replacement": {
    name: "Заміна АКБ",
    headColumnData: [
      {
        name: "rowNumber",
        label: "№",
        initial: null,
        filter: false,
        sort: true,
      },
      {
        name: "date",
        label: "Дата",
        initial: null,
        filter: false,
        sort: true,
      },
      {
        name: "typeBattery",
        label: "Встановлений тип АКБ",
        initial: null,
        filter: false,
        sort: true,
      },
      {
        name: "numberOfBatteries",
        label: "К-сть АКБ",
        initial: null,
        filter: false,
        sort: true,
      },
      {
        name: "actions",
        label: "Дії",
        initial: null,
        filter: false,
        sort: false,
      },
    ],
    exceptionKeyColumn: [
      "id",
      "batteriesDirectoryId",
      "upsModelsDirectoryId",
      "batteriesDirectoryId",
      "otherEquipmentDirectoryId",
      "receiptId",
    ],
    initialFilters: {
      id: null,
      date: null,
      typeBattery: null,
      numberOfBatteries: null,
    },
    rcspan: false,
    expandbleRow: false,
    actionMode: "modify",
    staticHeight: 288,
    newRow: {},
  },
  "expenses-table": {
    name: "Витрати",
    headColumnData: [
      {
        name: "rowNumber",
        label: "№",
        initial: null,
        filter: false,
        sort: true,
        colspan: 1,
        rowspan: 2,
        width: 20,
        maxWidth: 20,
      },
      {
        name: "object",
        label: "Об'єкт",
        initial: null,
        filter: false,
        sort: false,
        colspan: 3,
        rowspan: 1,
        width: 50,
        maxWidth: 50,
      },
      {
        name: "producer",
        label: "Виробник",
        initial: null,
        filter: true,
        sort: true,
        colspan: 1,
        rowspan: 2,
        width: 100,
        maxWidth: 100,
      },
      {
        name: "model",
        label: "Модель",
        initial: null,
        filter: true,
        sort: true,
        colspan: 1,
        rowspan: 2,
        width: 60,
        maxWidth: 60,
      },
      {
        name: "voltage",
        label: "Потужність",
        initial: null,
        filter: false,
        sort: true,
        colspan: 1,
        rowspan: 2,
        width: 50,
        maxWidth: 50,
      },
      {
        name: "numberOfBatteries",
        label: "К-сть АКБ",
        initial: null,
        filter: false,
        sort: true,
        colspan: 1,
        rowspan: 2,
        width: 60,
        maxWidth: 60,
      },
      {
        name: "inventoryNumber",
        label: "Інвентарний номер",
        initial: null,
        filter: false,
        sort: true,
        colspan: 1,
        rowspan: 2,
        width: 100,
        maxWidth: 100,
      },
    ],
    exceptionKeyColumn: [
      "id",
      "upsModelsDirectoryId",
      "batteriesDirectoryId",
      "districtId",
      "objectId",
      "equipmentCardId",
      "actions",
    ],
    initialFilters: {
      id: null,
      producer: null,
      model: null,
      voltage: null,
      numberOfBatteries: null,
      inventoryNumber: null,
      typeBattery: null,
      dateOfLastBatteryReplacement: null,
    },
    rcspan: true,
    expandbleRow: false,
    actionMode: "modify",
    staticHeight: 236,
  },
};

export const getTableState = (tab: string): TableState => {
  return tableState[tab as keyof typeof tableState];
};
